### PR TITLE
Added ability to specify dns servers via vpn.env file.

### PR DESCRIPTION
**Pull request by jasonkoon**
If not set, revert to defaults (8.8.8.8 and 8.8.4.4).

### CODE REVIEW

**Review by fcojean — APPROVED** [review]

**Comment by fcojean** [comment]
Thank you for this merge request. It's included in tag 1.1.4.
I will publish it on docker hub soon.

**Comment by djkazic** [comment]
Is this pushed to dockerhub? This is the exact feature I'm looking for. Thanks!

**Comment by fcojean** [comment]
Yes it is. Look for tags 1.1.4 or 1.1.5 which is the latest published.

https://hub.docker.com/r/fcojean/l2tp-ipsec-vpn-server/tags

**Comment by djkazic** [comment]
OK thanks!

**Pull request merged**
